export const INDIAN_DOG_BREEDS = [
  'Indian Pariah / Desi Dog',
  'Golden Retriever',
  'Labrador Retriever',
  'German Shepherd',
  'Beagle',
  'Pug',
  'Pomeranian',
  'Shih Tzu',
  'Mudhol Hound',
  'Rajapalayam',
  'Chippiparai',
  'Kanni',
  'Gaddi Kutta / Himalayan Sheepdog',
  'Rampur Greyhound',
  'Combai',
  'Bakharwal Dog',
  'Jonangi',
  'Pandikona',
  'Poodle',
  'Siberian Husky',
  'Rottweiler',
  'Doberman Pinscher',
  'French Bulldog',
  'Cocker Spaniel',
  'Great Dane',
  'Dachshund',
  'Boxer',
  'Chihuahua',
  'Maltese',
  'Lhasa Apso',
  'Tibetan Mastiff',
  'Indie / Mixed Breed',
  'Other Breed',
];
